# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
